runtime: php55
api_version: 1

handlers:
    
- url: /(.*\.(js|css|jpg))$
  static_files: static/\1
  upload: .*\.(js|css|jpg)$
   
- url: /public/favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  
- url: /.*
  script: public/index.php
